export default [
{"Name":"Bernd Leno","Club":"Arsenal","Nationality":"GER","Position":"GK","Age":"28","Matches":"35","Starts":"35","Mins":"3131","Goals":"0","Assists":"0","Passes_Attempted":"1156","Perc_Passes_Completed":"79.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"1"},
{"Name":"Bukayo Saka","Club":"Arsenal","Nationality":"ENG","Position":"FW,DF","Age":"18","Matches":"32","Starts":"30","Mins":"2553","Goals":"5","Assists":"3","Passes_Attempted":"1155","Perc_Passes_Completed":"74.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.24","xA":"0.17","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Granit Xhaka","Club":"Arsenal","Nationality":"SUI","Position":"MF,DF","Age":"27","Matches":"31","Starts":"29","Mins":"2522","Goals":"1","Assists":"2","Passes_Attempted":"2164","Perc_Passes_Completed":"89.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.03","xA":"0.06","Yellow_Cards":"7","Red_Cards":"1"},
{"Name":"Rob Holding","Club":"Arsenal","Nationality":"ENG","Position":"DF","Age":"24","Matches":"30","Starts":"28","Mins":"2558","Goals":"0","Assists":"1","Passes_Attempted":"1768","Perc_Passes_Completed":"89.3","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.04","xA":"0.01","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Pierre-Emerick Aubameyang","Club":"Arsenal","Nationality":"GAB","Position":"FW","Age":"31","Matches":"29","Starts":"26","Mins":"2332","Goals":"10","Assists":"3","Passes_Attempted":"691","Perc_Passes_Completed":"75.0","Penalty_Goals":"2","Penalty_Attempted":"2","xG":"0.41","xA":"0.11","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Kieran Tierney","Club":"Arsenal","Nationality":"SCO","Position":"DF","Age":"23","Matches":"27","Starts":"26","Mins":"2299","Goals":"1","Assists":"3","Passes_Attempted":"1490","Perc_Passes_Completed":"76.2","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.02","xA":"0.16","Yellow_Cards":"4","Red_Cards":"0"},
{"Name":"Héctor Bellerín","Club":"Arsenal","Nationality":"ESP","Position":"DF","Age":"25","Matches":"25","Starts":"24","Mins":"2089","Goals":"1","Assists":"2","Passes_Attempted":"1302","Perc_Passes_Completed":"82.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.04","xA":"0.1","Yellow_Cards":"8","Red_Cards":"0"}
,
{"Name":"Gabriel Dos Santos","Club":"Arsenal","Nationality":"BRA","Position":"DF","Age":"22","Matches":"23","Starts":"22","Mins":"1996","Goals":"2","Assists":"0","Passes_Attempted":"1492","Perc_Passes_Completed":"86.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.05","xA":"0.0","Yellow_Cards":"4","Red_Cards":"1"},
{"Name":"Alexandre Lacazette","Club":"Arsenal","Nationality":"FRA","Position":"FW","Age":"29","Matches":"31","Starts":"22","Mins":"1923","Goals":"13","Assists":"2","Passes_Attempted":"524","Perc_Passes_Completed":"78.2","Penalty_Goals":"3","Penalty_Attempted":"3","xG":"0.46","xA":"0.13","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Thomas Partey","Club":"Arsenal","Nationality":"GHA","Position":"MF","Age":"27","Matches":"24","Starts":"18","Mins":"1534","Goals":"0","Assists":"2","Passes_Attempted":"1112","Perc_Passes_Completed":"86.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.08","xA":"0.06","Yellow_Cards":"5","Red_Cards":"0"},
{"Name":"Emile Smith-Rowe","Club":"Arsenal","Nationality":"ENG","Position":"MF,FW","Age":"20","Matches":"20","Starts":"18","Mins":"1440","Goals":"2","Assists":"4","Passes_Attempted":"724","Perc_Passes_Completed":"87.7","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.13","xA":"0.18","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Dani Ceballos","Club":"Arsenal","Nationality":"ESP","Position":"MF","Age":"23","Matches":"25","Starts":"17","Mins":"1615","Goals":"0","Assists":"3","Passes_Attempted":"1286","Perc_Passes_Completed":"86.5","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.04","xA":"0.16","Yellow_Cards":"4","Red_Cards":"0"},
{"Name":"Mohamed Elneny","Club":"Arsenal","Nationality":"EGY","Position":"MF","Age":"28","Matches":"23","Starts":"17","Mins":"1544","Goals":"1","Assists":"0","Passes_Attempted":"1003","Perc_Passes_Completed":"93.4","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.03","xA":"0.01","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"David Luiz","Club":"Arsenal","Nationality":"BRA","Position":"DF","Age":"33","Matches":"20","Starts":"17","Mins":"1396","Goals":"1","Assists":"0","Passes_Attempted":"965","Perc_Passes_Completed":"83.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.06","xA":"0.03","Yellow_Cards":"1","Red_Cards":"1"},
{"Name":"Nicolas Pépé","Club":"Arsenal","Nationality":"CIV","Position":"FW","Age":"25","Matches":"29","Starts":"16","Mins":"1616","Goals":"10","Assists":"1","Passes_Attempted":"674","Perc_Passes_Completed":"75.7","Penalty_Goals":"1","Penalty_Attempted":"1","xG":"0.39","xA":"0.05","Yellow_Cards":"1","Red_Cards":"1"}
,
{"Name":"Willian","Club":"Arsenal","Nationality":"BRA","Position":"FW,MF","Age":"31","Matches":"25","Starts":"16","Mins":"1406","Goals":"1","Assists":"5","Passes_Attempted":"787","Perc_Passes_Completed":"79.3","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.13","xA":"0.16","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Pablo Marí","Club":"Arsenal","Nationality":"ESP","Position":"DF","Age":"26","Matches":"10","Starts":"10","Mins":"900","Goals":"0","Assists":"0","Passes_Attempted":"592","Perc_Passes_Completed":"90.7","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"2","Red_Cards":"0"}
,
{"Name":"Martin Ødegaard","Club":"Arsenal","Nationality":"NOR","Position":"MF","Age":"21","Matches":"14","Starts":"9","Mins":"866","Goals":"1","Assists":"2","Passes_Attempted":"521","Perc_Passes_Completed":"86.4","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.11","xA":"0.22","Yellow_Cards":"0","Red_Cards":"0"}
,
{"Name":"Calum Chambers","Club":"Arsenal","Nationality":"ENG","Position":"DF","Age":"25","Matches":"10","Starts":"8","Mins":"753","Goals":"0","Assists":"2","Passes_Attempted":"575","Perc_Passes_Completed":"80.3","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.07","xA":"0.14","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Cédric Soares","Club":"Arsenal","Nationality":"POR","Position":"DF","Age":"28","Matches":"10","Starts":"8","Mins":"746","Goals":"0","Assists":"1","Passes_Attempted":"463","Perc_Passes_Completed":"75.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.03","xA":"0.11","Yellow_Cards":"1","Red_Cards":"0"}
,
{"Name":"Martinelli","Club":"Arsenal","Nationality":"BRA","Position":"FW","Age":"19","Matches":"14","Starts":"7","Mins":"589","Goals":"2","Assists":"1","Passes_Attempted":"159","Perc_Passes_Completed":"79.2","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.53","xA":"0.32","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Ainsley Maitland-Niles","Club":"Arsenal","Nationality":"ENG","Position":"DF","Age":"22","Matches":"11","Starts":"5","Mins":"490","Goals":"0","Assists":"0","Passes_Attempted":"288","Perc_Passes_Completed":"78.5","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.02","xA":"0.04","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Eddie Nketiah","Club":"Arsenal","Nationality":"ENG","Position":"FW","Age":"21","Matches":"17","Starts":"4","Mins":"423","Goals":"2","Assists":"1","Passes_Attempted":"89","Perc_Passes_Completed":"82.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.52","xA":"0.18","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Mathew Ryan","Club":"Arsenal","Nationality":"AUS","Position":"GK","Age":"28","Matches":"3","Starts":"3","Mins":"270","Goals":"0","Assists":"0","Passes_Attempted":"67","Perc_Passes_Completed":"92.5","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Joe Willock","Club":"Arsenal","Nationality":"ENG","Position":"MF","Age":"20","Matches":"7","Starts":"2","Mins":"238","Goals":"0","Assists":"0","Passes_Attempted":"91","Perc_Passes_Completed":"75.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.17","xA":"0.02","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Sead Kolašinac","Club":"Arsenal","Nationality":"BIH","Position":"DF","Age":"27","Matches":"1","Starts":"1","Mins":"90","Goals":"0","Assists":"0","Passes_Attempted":"64","Perc_Passes_Completed":"84.4","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"}
,
{"Name":"Reiss Nelson","Club":"Arsenal","Nationality":"ENG","Position":"FW","Age":"20","Matches":"2","Starts":"0","Mins":"71","Goals":"0","Assists":"0","Passes_Attempted":"30","Perc_Passes_Completed":"56.7","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.06","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Shkodran Mustafi","Club":"Arsenal","Nationality":"GER","Position":"DF","Age":"28","Matches":"3","Starts":"0","Mins":"47","Goals":"0","Assists":"0","Passes_Attempted":"48","Perc_Passes_Completed":"85.4","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Rúnar Alex Rúnarsson","Club":"Arsenal","Nationality":"ISL","Position":"GK","Age":"25","Matches":"1","Starts":"0","Mins":"16","Goals":"0","Assists":"0","Passes_Attempted":"11","Perc_Passes_Completed":"63.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"}
,
];