export default [
{"Name":"Edouard Mendy","Club":"Chelsea","Nationality":"SEN","Position":"GK","Age":"28","Matches":"31","Starts":"31","Mins":"2745","Goals":"0","Assists":"0","Passes_Attempted":"1007","Perc_Passes_Completed":"84.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Timo Werner","Club":"Chelsea","Nationality":"GER","Position":"FW","Age":"24","Matches":"35","Starts":"29","Mins":"2602","Goals":"6","Assists":"8","Passes_Attempted":"826","Perc_Passes_Completed":"77.2","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.41","xA":"0.21","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Ben Chilwell","Club":"Chelsea","Nationality":"ENG","Position":"DF","Age":"23","Matches":"27","Starts":"27","Mins":"2286","Goals":"3","Assists":"5","Passes_Attempted":"1806","Perc_Passes_Completed":"78.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.1","xA":"0.11","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Reece James","Club":"Chelsea","Nationality":"ENG","Position":"DF","Age":"20","Matches":"32","Starts":"25","Mins":"2373","Goals":"1","Assists":"2","Passes_Attempted":"1987","Perc_Passes_Completed":"85.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.06","xA":"0.12","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"César Azpilicueta","Club":"Chelsea","Nationality":"ESP","Position":"DF","Age":"30","Matches":"26","Starts":"24","Mins":"2188","Goals":"1","Assists":"2","Passes_Attempted":"2015","Perc_Passes_Completed":"87.5","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.03","xA":"0.11","Yellow_Cards":"5","Red_Cards":"1"}
,
{"Name":"N'Golo Kanté","Club":"Chelsea","Nationality":"FRA","Position":"MF","Age":"29","Matches":"30","Starts":"24","Mins":"2146","Goals":"0","Assists":"2","Passes_Attempted":"1504","Perc_Passes_Completed":"86.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.04","xA":"0.05","Yellow_Cards":"7","Red_Cards":"0"}
,
{"Name":"Jorginho","Club":"Chelsea","Nationality":"ITA","Position":"MF","Age":"28","Matches":"28","Starts":"23","Mins":"2010","Goals":"7","Assists":"1","Passes_Attempted":"1739","Perc_Passes_Completed":"89.5","Penalty_Goals":"7","Penalty_Attempted":"9","xG":"0.31","xA":"0.09","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Thiago Silva","Club":"Chelsea","Nationality":"BRA","Position":"DF","Age":"35","Matches":"23","Starts":"23","Mins":"1935","Goals":"2","Assists":"0","Passes_Attempted":"1871","Perc_Passes_Completed":"93.5","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.05","xA":"0.02","Yellow_Cards":"5","Red_Cards":"1"},
{"Name":"Kurt Zouma","Club":"Chelsea","Nationality":"FRA","Position":"DF","Age":"25","Matches":"24","Starts":"22","Mins":"2029","Goals":"5","Assists":"0","Passes_Attempted":"1720","Perc_Passes_Completed":"91.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.08","xA":"0.0","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Mateo Kovačić","Club":"Chelsea","Nationality":"CRO","Position":"MF","Age":"26","Matches":"27","Starts":"21","Mins":"1815","Goals":"0","Assists":"1","Passes_Attempted":"1737","Perc_Passes_Completed":"91.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.05","xA":"0.09","Yellow_Cards":"4","Red_Cards":"0"}
,
{"Name":"Antonio Rüdiger","Club":"Chelsea","Nationality":"GER","Position":"DF","Age":"27","Matches":"19","Starts":"19","Mins":"1710","Goals":"1","Assists":"0","Passes_Attempted":"1476","Perc_Passes_Completed":"90.7","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.06","xA":"0.02","Yellow_Cards":"0","Red_Cards":"0"}
,
{"Name":"Christian Pulisic","Club":"Chelsea","Nationality":"USA","Position":"FW,MF","Age":"21","Matches":"27","Starts":"18","Mins":"1738","Goals":"4","Assists":"2","Passes_Attempted":"690","Perc_Passes_Completed":"80.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.28","xA":"0.14","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Kai Havertz","Club":"Chelsea","Nationality":"GER","Position":"MF,FW","Age":"21","Matches":"27","Starts":"18","Mins":"1520","Goals":"4","Assists":"3","Passes_Attempted":"765","Perc_Passes_Completed":"86.1","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.37","xA":"0.09","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Andreas Christensen","Club":"Chelsea","Nationality":"DEN","Position":"DF","Age":"24","Matches":"17","Starts":"15","Mins":"1371","Goals":"0","Assists":"0","Passes_Attempted":"1089","Perc_Passes_Completed":"92.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.01","xA":"0.02","Yellow_Cards":"2","Red_Cards":"1"},
{"Name":"Hakim Ziyech","Club":"Chelsea","Nationality":"MAR","Position":"FW,MF","Age":"27","Matches":"23","Starts":"15","Mins":"1172","Goals":"2","Assists":"3","Passes_Attempted":"734","Perc_Passes_Completed":"74.7","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.15","xA":"0.28","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Tammy Abraham","Club":"Chelsea","Nationality":"ENG","Position":"FW","Age":"22","Matches":"22","Starts":"12","Mins":"1040","Goals":"6","Assists":"1","Passes_Attempted":"218","Perc_Passes_Completed":"68.3","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.56","xA":"0.07","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Marcos Alonso","Club":"Chelsea","Nationality":"ESP","Position":"DF","Age":"29","Matches":"13","Starts":"11","Mins":"960","Goals":"2","Assists":"0","Passes_Attempted":"592","Perc_Passes_Completed":"81.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.16","xA":"0.11","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Callum Hudson-Odoi","Club":"Chelsea","Nationality":"ENG","Position":"FW,DF","Age":"19","Matches":"23","Starts":"10","Mins":"1059","Goals":"2","Assists":"3","Passes_Attempted":"659","Perc_Passes_Completed":"82.2","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.12","xA":"0.26","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Olivier Giroud","Club":"Chelsea","Nationality":"FRA","Position":"FW","Age":"33","Matches":"17","Starts":"8","Mins":"748","Goals":"4","Assists":"0","Passes_Attempted":"217","Perc_Passes_Completed":"74.2","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.58","xA":"0.09","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Kepa Arrizabalaga","Club":"Chelsea","Nationality":"ESP","Position":"GK","Age":"25","Matches":"7","Starts":"6","Mins":"585","Goals":"0","Assists":"0","Passes_Attempted":"243","Perc_Passes_Completed":"81.5","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Billy Gilmour","Club":"Chelsea","Nationality":"SCO","Position":"MF","Age":"19","Matches":"5","Starts":"3","Mins":"261","Goals":"0","Assists":"0","Passes_Attempted":"215","Perc_Passes_Completed":"89.3","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.01","xA":"0.04","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Willy Caballero","Club":"Chelsea","Nationality":"ARG","Position":"GK","Age":"38","Matches":"1","Starts":"1","Mins":"90","Goals":"0","Assists":"0","Passes_Attempted":"26","Perc_Passes_Completed":"92.3","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Ruben Loftus-Cheek","Club":"Chelsea","Nationality":"ENG","Position":"FW","Age":"24","Matches":"1","Starts":"1","Mins":"60","Goals":"0","Assists":"0","Passes_Attempted":"16","Perc_Passes_Completed":"68.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Emerson Palmieri","Club":"Chelsea","Nationality":"ITA","Position":"DF","Age":"25","Matches":"2","Starts":"0","Mins":"90","Goals":"0","Assists":"0","Passes_Attempted":"63","Perc_Passes_Completed":"81.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Fikayo Tomori","Club":"Chelsea","Nationality":"ENG","Position":"DF","Age":"22","Matches":"1","Starts":"0","Mins":"45","Goals":"0","Assists":"0","Passes_Attempted":"29","Perc_Passes_Completed":"93.1","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Ross Barkley","Club":"Chelsea","Nationality":"ENG","Position":"MF","Age":"26","Matches":"2","Starts":"0","Mins":"42","Goals":"0","Assists":"0","Passes_Attempted":"26","Perc_Passes_Completed":"84.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.06","xA":"0.16","Yellow_Cards":"0","Red_Cards":"0"},
];