export default [
{"Name":"Michael Keane","Club":"Everton","Nationality":"ENG","Position":"DF","Age":"27","Matches":"35","Starts":"33","Mins":"2991","Goals":"3","Assists":"1","Passes_Attempted":"1835","Perc_Passes_Completed":"88.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.04","xA":"0.03","Yellow_Cards":"4","Red_Cards":"0"},
{"Name":"Richarlison","Club":"Everton","Nationality":"BRA","Position":"FW","Age":"23","Matches":"34","Starts":"33","Mins":"2861","Goals":"7","Assists":"3","Passes_Attempted":"772","Perc_Passes_Completed":"69.2","Penalty_Goals":"1","Penalty_Attempted":"1","xG":"0.36","xA":"0.1","Yellow_Cards":"4","Red_Cards":"1"},
{"Name":"Dominic Calvert-Lewin","Club":"Everton","Nationality":"ENG","Position":"FW","Age":"23","Matches":"33","Starts":"32","Mins":"2871","Goals":"16","Assists":"0","Passes_Attempted":"669","Perc_Passes_Completed":"71.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.48","xA":"0.06","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Jordan Pickford","Club":"Everton","Nationality":"ENG","Position":"GK","Age":"26","Matches":"31","Starts":"31","Mins":"2742","Goals":"0","Assists":"0","Passes_Attempted":"1152","Perc_Passes_Completed":"66.1","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Lucas Digne","Club":"Everton","Nationality":"FRA","Position":"DF","Age":"27","Matches":"30","Starts":"30","Mins":"2681","Goals":"0","Assists":"7","Passes_Attempted":"1690","Perc_Passes_Completed":"72.5","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.02","xA":"0.18","Yellow_Cards":"2","Red_Cards":"1"},
{"Name":"Ben Godfrey","Club":"Everton","Nationality":"ENG","Position":"DF","Age":"22","Matches":"31","Starts":"29","Mins":"2685","Goals":"0","Assists":"2","Passes_Attempted":"1302","Perc_Passes_Completed":"84.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.03","xA":"0.02","Yellow_Cards":"4","Red_Cards":"0"},
{"Name":"Abdoulaye Doucouré","Club":"Everton","Nationality":"FRA","Position":"MF","Age":"27","Matches":"29","Starts":"29","Mins":"2443","Goals":"2","Assists":"3","Passes_Attempted":"1332","Perc_Passes_Completed":"86.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.08","xA":"0.08","Yellow_Cards":"6","Red_Cards":"0"}
,
{"Name":"Mason Holgate","Club":"Everton","Nationality":"ENG","Position":"DF","Age":"23","Matches":"28","Starts":"26","Mins":"2287","Goals":"1","Assists":"0","Passes_Attempted":"1200","Perc_Passes_Completed":"78.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.03","xA":"0.03","Yellow_Cards":"9","Red_Cards":"0"},
{"Name":"Gylfi Sigurðsson","Club":"Everton","Nationality":"ISL","Position":"MF","Age":"30","Matches":"36","Starts":"24","Mins":"2253","Goals":"6","Assists":"5","Passes_Attempted":"947","Perc_Passes_Completed":"79.1","Penalty_Goals":"3","Penalty_Attempted":"4","xG":"0.27","xA":"0.19","Yellow_Cards":"2","Red_Cards":"0"}
,
{"Name":"Allan","Club":"Everton","Nationality":"BRA","Position":"MF","Age":"29","Matches":"24","Starts":"23","Mins":"2051","Goals":"0","Assists":"0","Passes_Attempted":"1048","Perc_Passes_Completed":"85.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.01","xA":"0.04","Yellow_Cards":"6","Red_Cards":"0"},
{"Name":"Yerry Mina","Club":"Everton","Nationality":"COL","Position":"DF","Age":"25","Matches":"24","Starts":"23","Mins":"1937","Goals":"2","Assists":"0","Passes_Attempted":"1227","Perc_Passes_Completed":"90.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.06","xA":"0.0","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"James Rodríguez","Club":"Everton","Nationality":"COL","Position":"FW,MF","Age":"29","Matches":"23","Starts":"21","Mins":"1764","Goals":"6","Assists":"4","Passes_Attempted":"1111","Perc_Passes_Completed":"79.1","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.17","xA":"0.28","Yellow_Cards":"4","Red_Cards":"0"}
,
{"Name":"Séamus Coleman","Club":"Everton","Nationality":"IRL","Position":"DF,MF","Age":"31","Matches":"25","Starts":"18","Mins":"1613","Goals":"0","Assists":"3","Passes_Attempted":"766","Perc_Passes_Completed":"81.5","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.06","xA":"0.11","Yellow_Cards":"0","Red_Cards":"0"}
,
{"Name":"André Gomes","Club":"Everton","Nationality":"POR","Position":"MF","Age":"27","Matches":"28","Starts":"17","Mins":"1570","Goals":"0","Assists":"1","Passes_Attempted":"901","Perc_Passes_Completed":"83.2","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.03","xA":"0.05","Yellow_Cards":"3","Red_Cards":"0"}
,
{"Name":"Alex Iwobi","Club":"Everton","Nationality":"NGA","Position":"FW,DF","Age":"24","Matches":"30","Starts":"17","Mins":"1542","Goals":"1","Assists":"2","Passes_Attempted":"688","Perc_Passes_Completed":"77.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.06","xA":"0.11","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Tom Davies","Club":"Everton","Nationality":"ENG","Position":"MF","Age":"22","Matches":"25","Starts":"17","Mins":"1423","Goals":"0","Assists":"1","Passes_Attempted":"684","Perc_Passes_Completed":"83.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.01","xA":"0.06","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Robin Olsen","Club":"Everton","Nationality":"SWE","Position":"GK","Age":"30","Matches":"7","Starts":"7","Mins":"630","Goals":"0","Assists":"0","Passes_Attempted":"199","Perc_Passes_Completed":"71.4","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Bernard","Club":"Everton","Nationality":"BRA","Position":"MF,FW","Age":"27","Matches":"12","Starts":"3","Mins":"455","Goals":"1","Assists":"0","Passes_Attempted":"272","Perc_Passes_Completed":"79.4","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.04","xA":"0.13","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Fabian Delph","Club":"Everton","Nationality":"ENG","Position":"MF,DF","Age":"30","Matches":"8","Starts":"2","Mins":"266","Goals":"0","Assists":"0","Passes_Attempted":"234","Perc_Passes_Completed":"88.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.01","xA":"0.03","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Anthony Gordon","Club":"Everton","Nationality":"ENG","Position":"FW,MF","Age":"19","Matches":"3","Starts":"1","Mins":"88","Goals":"0","Assists":"0","Passes_Attempted":"26","Perc_Passes_Completed":"84.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.03","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Niels Nkounkou","Club":"Everton","Nationality":"FRA","Position":"DF,FW","Age":"19","Matches":"2","Starts":"1","Mins":"81","Goals":"0","Assists":"0","Passes_Attempted":"34","Perc_Passes_Completed":"79.4","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.02","xA":"0.0","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Jonjoe Kenny","Club":"Everton","Nationality":"ENG","Position":"DF","Age":"23","Matches":"4","Starts":"1","Mins":"79","Goals":"0","Assists":"0","Passes_Attempted":"61","Perc_Passes_Completed":"77.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Joshua King","Club":"Everton","Nationality":"NOR","Position":"MF,FW","Age":"28","Matches":"11","Starts":"0","Mins":"148","Goals":"0","Assists":"0","Passes_Attempted":"48","Perc_Passes_Completed":"70.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.48","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Cenk Tosun","Club":"Everton","Nationality":"TUR","Position":"FW","Age":"29","Matches":"5","Starts":"0","Mins":"48","Goals":"0","Assists":"0","Passes_Attempted":"10","Perc_Passes_Completed":"80.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.25","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"João Virgínia","Club":"Everton","Nationality":"POR","Position":"GK","Age":"20","Matches":"1","Starts":"0","Mins":"48","Goals":"0","Assists":"0","Passes_Attempted":"17","Perc_Passes_Completed":"52.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"}
,
{"Name":"Moise Kean","Club":"Everton","Nationality":"ITA","Position":"FW","Age":"20","Matches":"2","Starts":"0","Mins":"15","Goals":"0","Assists":"0","Passes_Attempted":"9","Perc_Passes_Completed":"77.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.21","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Theo Walcott","Club":"Everton","Nationality":"ENG","Position":"FW","Age":"31","Matches":"1","Starts":"0","Mins":"13","Goals":"0","Assists":"0","Passes_Attempted":"1","Perc_Passes_Completed":"100.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Jean-Philippe Gbamin","Club":"Everton","Nationality":"CIV","Position":"MF","Age":"24","Matches":"1","Starts":"0","Mins":"12","Goals":"0","Assists":"0","Passes_Attempted":"9","Perc_Passes_Completed":"66.7","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Nathan Broadhead","Club":"Everton","Nationality":"WAL","Position":"MF","Age":"22","Matches":"1","Starts":"0","Mins":"3","Goals":"0","Assists":"0","Passes_Attempted":"2","Perc_Passes_Completed":"100.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
];