export default [
{"Name":"Andrew Robertson","Club":"Liverpool FC","Nationality":"SCO","Position":"DF","Age":"26","Matches":"38","Starts":"38","Mins":"3383","Goals":"1","Assists":"7","Passes_Attempted":"3214","Perc_Passes_Completed":"79.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.04","xA":"0.18","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Mohamed Salah","Club":"Liverpool FC","Nationality":"EGY","Position":"FW","Age":"28","Matches":"37","Starts":"34","Mins":"3078","Goals":"22","Assists":"5","Passes_Attempted":"1288","Perc_Passes_Completed":"83.2","Penalty_Goals":"6","Penalty_Attempted":"6","xG":"0.61","xA":"0.18","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Trent Alexander-Arnold","Club":"Liverpool FC","Nationality":"ENG","Position":"DF","Age":"21","Matches":"36","Starts":"34","Mins":"3031","Goals":"2","Assists":"7","Passes_Attempted":"2941","Perc_Passes_Completed":"75.3","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.08","xA":"0.24","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Georginio Wijnaldum","Club":"Liverpool FC","Nationality":"NED","Position":"MF","Age":"29","Matches":"38","Starts":"34","Mins":"2941","Goals":"2","Assists":"0","Passes_Attempted":"1747","Perc_Passes_Completed":"93.3","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.1","xA":"0.05","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Alisson","Club":"Liverpool FC","Nationality":"BRA","Position":"GK","Age":"27","Matches":"33","Starts":"33","Mins":"2970","Goals":"1","Assists":"0","Passes_Attempted":"1137","Perc_Passes_Completed":"85.2","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Roberto Firmino","Club":"Liverpool FC","Nationality":"BRA","Position":"FW","Age":"28","Matches":"36","Starts":"33","Mins":"2838","Goals":"9","Assists":"7","Passes_Attempted":"1308","Perc_Passes_Completed":"79.7","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.4","xA":"0.2","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Sadio Mané","Club":"Liverpool FC","Nationality":"SEN","Position":"FW","Age":"28","Matches":"35","Starts":"31","Mins":"2810","Goals":"11","Assists":"7","Passes_Attempted":"1064","Perc_Passes_Completed":"75.4","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.49","xA":"0.18","Yellow_Cards":"3","Red_Cards":"0"}
,
{"Name":"Fabinho","Club":"Liverpool FC","Nationality":"BRA","Position":"DF,MF","Age":"26","Matches":"30","Starts":"28","Mins":"2567","Goals":"0","Assists":"0","Passes_Attempted":"2049","Perc_Passes_Completed":"91.1","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.02","xA":"0.01","Yellow_Cards":"6","Red_Cards":"0"},
{"Name":"Thiago Alcántara","Club":"Liverpool FC","Nationality":"ESP","Position":"MF","Age":"29","Matches":"24","Starts":"20","Mins":"1854","Goals":"1","Assists":"0","Passes_Attempted":"1674","Perc_Passes_Completed":"89.5","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.07","xA":"0.11","Yellow_Cards":"4","Red_Cards":"0"}
,
{"Name":"Jordan Henderson","Club":"Liverpool FC","Nationality":"ENG","Position":"MF,DF","Age":"30","Matches":"21","Starts":"20","Mins":"1704","Goals":"1","Assists":"1","Passes_Attempted":"1812","Perc_Passes_Completed":"86.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.09","xA":"0.07","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Nathaniel Phillips","Club":"Liverpool FC","Nationality":"ENG","Position":"DF","Age":"23","Matches":"17","Starts":"15","Mins":"1456","Goals":"1","Assists":"1","Passes_Attempted":"1058","Perc_Passes_Completed":"87.2","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.07","xA":"0.02","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Curtis Jones","Club":"Liverpool FC","Nationality":"ENG","Position":"MF","Age":"19","Matches":"24","Starts":"13","Mins":"1179","Goals":"1","Assists":"2","Passes_Attempted":"976","Perc_Passes_Completed":"91.2","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.11","xA":"0.12","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Diogo Jota","Club":"Liverpool FC","Nationality":"POR","Position":"FW","Age":"23","Matches":"19","Starts":"12","Mins":"1112","Goals":"9","Assists":"0","Passes_Attempted":"451","Perc_Passes_Completed":"72.5","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.53","xA":"0.13","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"James Milner","Club":"Liverpool FC","Nationality":"ENG","Position":"MF,DF","Age":"34","Matches":"26","Starts":"11","Mins":"1070","Goals":"0","Assists":"1","Passes_Attempted":"913","Perc_Passes_Completed":"84.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.04","xA":"0.1","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Ozan Kabak","Club":"Liverpool FC","Nationality":"TUR","Position":"DF","Age":"20","Matches":"9","Starts":"9","Mins":"801","Goals":"0","Assists":"0","Passes_Attempted":"554","Perc_Passes_Completed":"90.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.01","xA":"0.02","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Joël Matip","Club":"Liverpool FC","Nationality":"CMR","Position":"DF","Age":"28","Matches":"10","Starts":"9","Mins":"691","Goals":"1","Assists":"2","Passes_Attempted":"527","Perc_Passes_Completed":"88.4","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.08","xA":"0.14","Yellow_Cards":"2","Red_Cards":"0"}
,
{"Name":"Rhys Williams","Club":"Liverpool FC","Nationality":"ENG","Position":"DF","Age":"19","Matches":"9","Starts":"7","Mins":"661","Goals":"0","Assists":"0","Passes_Attempted":"451","Perc_Passes_Completed":"92.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.07","xA":"0.05","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Naby Keïta","Club":"Liverpool FC","Nationality":"GUI","Position":"MF","Age":"25","Matches":"10","Starts":"7","Mins":"520","Goals":"0","Assists":"0","Passes_Attempted":"356","Perc_Passes_Completed":"87.4","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.09","xA":"0.14","Yellow_Cards":"1","Red_Cards":"0"}
,
{"Name":"Joe Gomez","Club":"Liverpool FC","Nationality":"ENG","Position":"DF","Age":"23","Matches":"7","Starts":"6","Mins":"590","Goals":"0","Assists":"0","Passes_Attempted":"532","Perc_Passes_Completed":"90.2","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Xherdan Shaqiri","Club":"Liverpool FC","Nationality":"SUI","Position":"MF,FW","Age":"28","Matches":"14","Starts":"5","Mins":"556","Goals":"0","Assists":"2","Passes_Attempted":"426","Perc_Passes_Completed":"83.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.06","xA":"0.49","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Virgil van Dijk","Club":"Liverpool FC","Nationality":"NED","Position":"DF","Age":"29","Matches":"5","Starts":"5","Mins":"370","Goals":"1","Assists":"0","Passes_Attempted":"329","Perc_Passes_Completed":"90.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.08","xA":"0.0","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Adrián","Club":"Liverpool FC","Nationality":"ESP","Position":"GK","Age":"33","Matches":"3","Starts":"3","Mins":"270","Goals":"0","Assists":"0","Passes_Attempted":"99","Perc_Passes_Completed":"76.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"}
,
{"Name":"Neco Williams","Club":"Liverpool FC","Nationality":"WAL","Position":"DF","Age":"19","Matches":"6","Starts":"3","Mins":"249","Goals":"0","Assists":"0","Passes_Attempted":"213","Perc_Passes_Completed":"73.2","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.03","xA":"0.1","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Takumi Minamino","Club":"Liverpool FC","Nationality":"JPN","Position":"MF,FW","Age":"25","Matches":"9","Starts":"2","Mins":"293","Goals":"1","Assists":"0","Passes_Attempted":"139","Perc_Passes_Completed":"79.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.2","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Alex Oxlade-Chamberlain","Club":"Liverpool FC","Nationality":"ENG","Position":"FW,MF","Age":"26","Matches":"13","Starts":"2","Mins":"253","Goals":"1","Assists":"1","Passes_Attempted":"138","Perc_Passes_Completed":"75.4","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.13","xA":"0.08","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Divock Origi","Club":"Liverpool FC","Nationality":"BEL","Position":"FW","Age":"25","Matches":"9","Starts":"2","Mins":"186","Goals":"0","Assists":"0","Passes_Attempted":"60","Perc_Passes_Completed":"76.7","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.47","xA":"0.11","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Caoimhín Kelleher","Club":"Liverpool FC","Nationality":"IRL","Position":"GK","Age":"21","Matches":"2","Starts":"2","Mins":"180","Goals":"0","Assists":"0","Passes_Attempted":"62","Perc_Passes_Completed":"82.3","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"}
,
{"Name":"Kostas Tsimikas","Club":"Liverpool FC","Nationality":"GRE","Position":"DF","Age":"24","Matches":"2","Starts":"0","Mins":"7","Goals":"0","Assists":"0","Passes_Attempted":"8","Perc_Passes_Completed":"75.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
];