export default [
{"Name":"Ederson","Club":"Manchester City","Nationality":"BRA","Position":"GK","Age":"26","Matches":"36","Starts":"36","Mins":"3240","Goals":"0","Assists":"1","Passes_Attempted":"1090","Perc_Passes_Completed":"83.1","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.01","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Rúben Dias","Club":"Manchester City","Nationality":"POR","Position":"DF","Age":"23","Matches":"32","Starts":"32","Mins":"2843","Goals":"1","Assists":"0","Passes_Attempted":"2671","Perc_Passes_Completed":"93.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.07","xA":"0.0","Yellow_Cards":"4","Red_Cards":"0"}
,
{"Name":"Rodri","Club":"Manchester City","Nationality":"ESP","Position":"MF","Age":"24","Matches":"34","Starts":"31","Mins":"2748","Goals":"2","Assists":"2","Passes_Attempted":"2728","Perc_Passes_Completed":"91.5","Penalty_Goals":"1","Penalty_Attempted":"1","xG":"0.08","xA":"0.06","Yellow_Cards":"6","Red_Cards":"0"},
{"Name":"Raheem Sterling","Club":"Manchester City","Nationality":"ENG","Position":"FW","Age":"25","Matches":"31","Starts":"28","Mins":"2536","Goals":"10","Assists":"7","Passes_Attempted":"1127","Perc_Passes_Completed":"85.4","Penalty_Goals":"0","Penalty_Attempted":"1","xG":"0.43","xA":"0.17","Yellow_Cards":"4","Red_Cards":"0"},
{"Name":"João Cancelo","Club":"Manchester City","Nationality":"POR","Position":"DF","Age":"26","Matches":"28","Starts":"27","Mins":"2299","Goals":"2","Assists":"3","Passes_Attempted":"2094","Perc_Passes_Completed":"85.7","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.08","xA":"0.19","Yellow_Cards":"5","Red_Cards":"1"}
,
{"Name":"Bernardo Silva","Club":"Manchester City","Nationality":"POR","Position":"MF,FW","Age":"25","Matches":"26","Starts":"24","Mins":"2065","Goals":"2","Assists":"6","Passes_Attempted":"1427","Perc_Passes_Completed":"89.7","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.12","xA":"0.16","Yellow_Cards":"5","Red_Cards":"0"},
{"Name":"İlkay Gündoğan","Club":"Manchester City","Nationality":"GER","Position":"MF","Age":"29","Matches":"28","Starts":"23","Mins":"2029","Goals":"13","Assists":"2","Passes_Attempted":"1707","Perc_Passes_Completed":"91.0","Penalty_Goals":"1","Penalty_Attempted":"2","xG":"0.4","xA":"0.2","Yellow_Cards":"1","Red_Cards":"0"}
,
{"Name":"Kevin De Bruyne","Club":"Manchester City","Nationality":"BEL","Position":"MF","Age":"29","Matches":"25","Starts":"23","Mins":"1997","Goals":"6","Assists":"12","Passes_Attempted":"1406","Perc_Passes_Completed":"76.0","Penalty_Goals":"2","Penalty_Attempted":"3","xG":"0.44","xA":"0.46","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Riyad Mahrez","Club":"Manchester City","Nationality":"ALG","Position":"FW","Age":"29","Matches":"27","Starts":"23","Mins":"1949","Goals":"9","Assists":"6","Passes_Attempted":"1086","Perc_Passes_Completed":"84.2","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.26","xA":"0.27","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Gabriel Jesus","Club":"Manchester City","Nationality":"BRA","Position":"FW","Age":"23","Matches":"29","Starts":"22","Mins":"2063","Goals":"9","Assists":"4","Passes_Attempted":"754","Perc_Passes_Completed":"84.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.38","xA":"0.15","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Kyle Walker","Club":"Manchester City","Nationality":"ENG","Position":"DF","Age":"30","Matches":"24","Starts":"22","Mins":"1946","Goals":"1","Assists":"1","Passes_Attempted":"1897","Perc_Passes_Completed":"89.4","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.01","xA":"0.02","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"John Stones","Club":"Manchester City","Nationality":"ENG","Position":"DF","Age":"26","Matches":"22","Starts":"22","Mins":"1933","Goals":"4","Assists":"0","Passes_Attempted":"1713","Perc_Passes_Completed":"94.3","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.1","xA":"0.0","Yellow_Cards":"0","Red_Cards":"1"},
{"Name":"Phil Foden","Club":"Manchester City","Nationality":"ENG","Position":"FW,MF","Age":"20","Matches":"28","Starts":"17","Mins":"1616","Goals":"9","Assists":"5","Passes_Attempted":"838","Perc_Passes_Completed":"82.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.31","xA":"0.23","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Oleksandr Zinchenko","Club":"Manchester City","Nationality":"UKR","Position":"DF","Age":"23","Matches":"20","Starts":"15","Mins":"1478","Goals":"0","Assists":"0","Passes_Attempted":"1475","Perc_Passes_Completed":"90.2","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.04","xA":"0.08","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Ferrán Torres","Club":"Manchester City","Nationality":"ESP","Position":"FW,MF","Age":"20","Matches":"24","Starts":"15","Mins":"1306","Goals":"7","Assists":"2","Passes_Attempted":"442","Perc_Passes_Completed":"81.4","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.37","xA":"0.13","Yellow_Cards":"1","Red_Cards":"0"}
,
{"Name":"Aymeric Laporte","Club":"Manchester City","Nationality":"FRA","Position":"DF","Age":"26","Matches":"16","Starts":"14","Mins":"1344","Goals":"0","Assists":"0","Passes_Attempted":"1261","Perc_Passes_Completed":"92.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.05","xA":"0.05","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Fernandinho","Club":"Manchester City","Nationality":"BRA","Position":"MF","Age":"35","Matches":"21","Starts":"12","Mins":"1188","Goals":"0","Assists":"2","Passes_Attempted":"1001","Perc_Passes_Completed":"87.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.06","xA":"0.07","Yellow_Cards":"6","Red_Cards":"0"},
{"Name":"Benjamin Mendy","Club":"Manchester City","Nationality":"FRA","Position":"DF","Age":"26","Matches":"13","Starts":"11","Mins":"953","Goals":"2","Assists":"1","Passes_Attempted":"651","Perc_Passes_Completed":"81.7","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.04","xA":"0.04","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Nathan Aké","Club":"Manchester City","Nationality":"NED","Position":"DF","Age":"25","Matches":"10","Starts":"9","Mins":"797","Goals":"1","Assists":"0","Passes_Attempted":"755","Perc_Passes_Completed":"93.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.01","xA":"0.0","Yellow_Cards":"4","Red_Cards":"0"}
,
{"Name":"Sergio Agüero","Club":"Manchester City","Nationality":"ARG","Position":"FW,MF","Age":"32","Matches":"12","Starts":"7","Mins":"559","Goals":"4","Assists":"1","Passes_Attempted":"170","Perc_Passes_Completed":"84.1","Penalty_Goals":"1","Penalty_Attempted":"2","xG":"0.54","xA":"0.21","Yellow_Cards":"0","Red_Cards":"0"}
,
{"Name":"Eric García","Club":"Manchester City","Nationality":"ESP","Position":"DF","Age":"19","Matches":"6","Starts":"3","Mins":"383","Goals":"0","Assists":"0","Passes_Attempted":"344","Perc_Passes_Completed":"93.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.03","xA":"0.02","Yellow_Cards":"0","Red_Cards":"0"}
,
{"Name":"Scott Carson","Club":"Manchester City","Nationality":"ENG","Position":"GK","Age":"34","Matches":"1","Starts":"1","Mins":"90","Goals":"0","Assists":"0","Passes_Attempted":"16","Perc_Passes_Completed":"93.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Zack Steffen","Club":"Manchester City","Nationality":"USA","Position":"GK","Age":"25","Matches":"1","Starts":"1","Mins":"90","Goals":"0","Assists":"0","Passes_Attempted":"28","Perc_Passes_Completed":"82.1","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Liam Delap","Club":"Manchester City","Nationality":"ENG","Position":"FW","Age":"17","Matches":"1","Starts":"0","Mins":"40","Goals":"0","Assists":"0","Passes_Attempted":"7","Perc_Passes_Completed":"71.4","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.06","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
];