export default [
{"Name":"Pierre Højbjerg","Club":"Tottenham Hotspur","Nationality":"DEN","Position":"MF","Age":"24","Matches":"38","Starts":"38","Mins":"3420","Goals":"2","Assists":"4","Passes_Attempted":"2687","Perc_Passes_Completed":"88.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.03","xA":"0.05","Yellow_Cards":"9","Red_Cards":"0"}
,
{"Name":"Hugo Lloris","Club":"Tottenham Hotspur","Nationality":"FRA","Position":"GK","Age":"33","Matches":"38","Starts":"38","Mins":"3420","Goals":"0","Assists":"0","Passes_Attempted":"1067","Perc_Passes_Completed":"71.5","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Son Heung-min","Club":"Tottenham Hotspur","Nationality":"KOR","Position":"FW","Age":"28","Matches":"37","Starts":"36","Mins":"3114","Goals":"17","Assists":"10","Passes_Attempted":"1199","Perc_Passes_Completed":"76.7","Penalty_Goals":"1","Penalty_Attempted":"1","xG":"0.3","xA":"0.26","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Harry Kane","Club":"Tottenham Hotspur","Nationality":"ENG","Position":"FW","Age":"27","Matches":"35","Starts":"35","Mins":"3082","Goals":"23","Assists":"14","Passes_Attempted":"937","Perc_Passes_Completed":"70.1","Penalty_Goals":"4","Penalty_Attempted":"4","xG":"0.6","xA":"0.22","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Eric Dier","Club":"Tottenham Hotspur","Nationality":"ENG","Position":"DF","Age":"26","Matches":"28","Starts":"28","Mins":"2520","Goals":"0","Assists":"0","Passes_Attempted":"1654","Perc_Passes_Completed":"84.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.03","xA":"0.0","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Tanguy Ndombele","Club":"Tottenham Hotspur","Nationality":"FRA","Position":"MF","Age":"23","Matches":"33","Starts":"28","Mins":"2091","Goals":"3","Assists":"2","Passes_Attempted":"1165","Perc_Passes_Completed":"85.3","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.06","xA":"0.1","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Sergio Reguilón","Club":"Tottenham Hotspur","Nationality":"ESP","Position":"DF","Age":"23","Matches":"27","Starts":"26","Mins":"2244","Goals":"0","Assists":"3","Passes_Attempted":"1393","Perc_Passes_Completed":"77.2","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.06","xA":"0.07","Yellow_Cards":"5","Red_Cards":"0"}
,
{"Name":"Toby Alderweireld","Club":"Tottenham Hotspur","Nationality":"BEL","Position":"DF","Age":"31","Matches":"25","Starts":"25","Mins":"2240","Goals":"1","Assists":"0","Passes_Attempted":"1366","Perc_Passes_Completed":"83.7","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.03","xA":"0.01","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Serge Aurier","Club":"Tottenham Hotspur","Nationality":"CIV","Position":"DF","Age":"27","Matches":"19","Starts":"19","Mins":"1605","Goals":"2","Assists":"3","Passes_Attempted":"954","Perc_Passes_Completed":"80.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.08","xA":"0.11","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Davinson Sánchez","Club":"Tottenham Hotspur","Nationality":"COL","Position":"DF","Age":"24","Matches":"18","Starts":"17","Mins":"1486","Goals":"0","Assists":"0","Passes_Attempted":"977","Perc_Passes_Completed":"86.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.07","xA":"0.0","Yellow_Cards":"1","Red_Cards":"0"}
,
{"Name":"Moussa Sissoko","Club":"Tottenham Hotspur","Nationality":"FRA","Position":"MF","Age":"30","Matches":"25","Starts":"15","Mins":"1585","Goals":"0","Assists":"0","Passes_Attempted":"792","Perc_Passes_Completed":"84.1","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.02","xA":"0.03","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Lucas Moura","Club":"Tottenham Hotspur","Nationality":"BRA","Position":"FW,MF","Age":"27","Matches":"30","Starts":"14","Mins":"1411","Goals":"3","Assists":"4","Passes_Attempted":"600","Perc_Passes_Completed":"74.7","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.14","xA":"0.14","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Ben Davies","Club":"Tottenham Hotspur","Nationality":"WAL","Position":"DF","Age":"27","Matches":"20","Starts":"14","Mins":"1346","Goals":"0","Assists":"1","Passes_Attempted":"783","Perc_Passes_Completed":"77.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.01","xA":"0.04","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Matt Doherty","Club":"Tottenham Hotspur","Nationality":"IRL","Position":"DF","Age":"28","Matches":"17","Starts":"13","Mins":"1240","Goals":"0","Assists":"2","Passes_Attempted":"826","Perc_Passes_Completed":"80.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.03","xA":"0.06","Yellow_Cards":"4","Red_Cards":"1"},
{"Name":"Steven Bergwijn","Club":"Tottenham Hotspur","Nationality":"NED","Position":"FW,MF","Age":"22","Matches":"21","Starts":"13","Mins":"1208","Goals":"1","Assists":"3","Passes_Attempted":"428","Perc_Passes_Completed":"81.1","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.18","xA":"0.09","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Giovani Lo Celso","Club":"Tottenham Hotspur","Nationality":"ARG","Position":"MF","Age":"24","Matches":"18","Starts":"11","Mins":"945","Goals":"1","Assists":"1","Passes_Attempted":"589","Perc_Passes_Completed":"78.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.11","xA":"0.12","Yellow_Cards":"5","Red_Cards":"0"},
{"Name":"Gareth Bale","Club":"Tottenham Hotspur","Nationality":"WAL","Position":"FW","Age":"31","Matches":"20","Starts":"10","Mins":"920","Goals":"11","Assists":"2","Passes_Attempted":"408","Perc_Passes_Completed":"69.6","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.52","xA":"0.19","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Harry Winks","Club":"Tottenham Hotspur","Nationality":"ENG","Position":"MF","Age":"24","Matches":"15","Starts":"9","Mins":"861","Goals":"0","Assists":"0","Passes_Attempted":"658","Perc_Passes_Completed":"84.2","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.01","xA":"0.03","Yellow_Cards":"5","Red_Cards":"0"},
{"Name":"Joe Rodon","Club":"Tottenham Hotspur","Nationality":"WAL","Position":"DF","Age":"22","Matches":"12","Starts":"8","Mins":"733","Goals":"0","Assists":"0","Passes_Attempted":"411","Perc_Passes_Completed":"88.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Dele Alli","Club":"Tottenham Hotspur","Nationality":"ENG","Position":"MF","Age":"24","Matches":"15","Starts":"7","Mins":"620","Goals":"0","Assists":"1","Passes_Attempted":"337","Perc_Passes_Completed":"80.1","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.2","xA":"0.13","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Japhet Tanganga","Club":"Tottenham Hotspur","Nationality":"ENG","Position":"DF","Age":"21","Matches":"6","Starts":"6","Mins":"487","Goals":"0","Assists":"0","Passes_Attempted":"229","Perc_Passes_Completed":"84.3","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.04","xA":"0.0","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Érik Lamela","Club":"Tottenham Hotspur","Nationality":"ARG","Position":"FW,MF","Age":"28","Matches":"23","Starts":"5","Mins":"717","Goals":"1","Assists":"0","Passes_Attempted":"368","Perc_Passes_Completed":"78.5","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.18","xA":"0.12","Yellow_Cards":"6","Red_Cards":"1"}
,
{"Name":"Carlos Vinícius","Club":"Tottenham Hotspur","Nationality":"BRA","Position":"FW","Age":"25","Matches":"9","Starts":"3","Mins":"308","Goals":"1","Assists":"0","Passes_Attempted":"44","Perc_Passes_Completed":"56.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.4","xA":"0.03","Yellow_Cards":"2","Red_Cards":"0"}
,
{"Name":"Dane Scarlett","Club":"Tottenham Hotspur","Nationality":"ENG","Position":"FW","Age":"16","Matches":"1","Starts":"0","Mins":"1","Goals":"0","Assists":"0","Passes_Attempted":"0","Perc_Passes_Completed":"-1.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
];