export default [
{"Name":"Tomáš Souček","Club":"West Ham United","Nationality":"CZE","Position":"MF","Age":"25","Matches":"38","Starts":"38","Mins":"3419","Goals":"10","Assists":"1","Passes_Attempted":"1539","Perc_Passes_Completed":"76.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.24","xA":"0.04","Yellow_Cards":"7","Red_Cards":"1"}
,
{"Name":"Aaron Cresswell","Club":"West Ham United","Nationality":"ENG","Position":"DF","Age":"30","Matches":"36","Starts":"36","Mins":"3170","Goals":"0","Assists":"8","Passes_Attempted":"2060","Perc_Passes_Completed":"74.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.03","xA":"0.17","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Łukasz Fabiański","Club":"West Ham United","Nationality":"POL","Position":"GK","Age":"35","Matches":"35","Starts":"35","Mins":"3150","Goals":"0","Assists":"0","Passes_Attempted":"1002","Perc_Passes_Completed":"60.5","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"2","Red_Cards":"0"}
,
{"Name":"Vladimír Coufal","Club":"West Ham United","Nationality":"CZE","Position":"DF","Age":"27","Matches":"34","Starts":"34","Mins":"3054","Goals":"0","Assists":"7","Passes_Attempted":"1692","Perc_Passes_Completed":"70.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.04","xA":"0.14","Yellow_Cards":"3","Red_Cards":"0"}
,
{"Name":"Declan Rice","Club":"West Ham United","Nationality":"ENG","Position":"MF","Age":"21","Matches":"32","Starts":"32","Mins":"2879","Goals":"2","Assists":"1","Passes_Attempted":"1506","Perc_Passes_Completed":"86.2","Penalty_Goals":"1","Penalty_Attempted":"2","xG":"0.1","xA":"0.06","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Pablo Fornals","Club":"West Ham United","Nationality":"ESP","Position":"FW,MF","Age":"24","Matches":"33","Starts":"31","Mins":"2572","Goals":"5","Assists":"4","Passes_Attempted":"1102","Perc_Passes_Completed":"77.3","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.23","xA":"0.09","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Jarrod Bowen","Club":"West Ham United","Nationality":"ENG","Position":"FW,MF","Age":"23","Matches":"38","Starts":"30","Mins":"2562","Goals":"8","Assists":"5","Passes_Attempted":"734","Perc_Passes_Completed":"68.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.22","xA":"0.16","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Angelo Ogbonna","Club":"West Ham United","Nationality":"ITA","Position":"DF","Age":"32","Matches":"28","Starts":"28","Mins":"2492","Goals":"3","Assists":"0","Passes_Attempted":"960","Perc_Passes_Completed":"84.4","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.05","xA":"0.04","Yellow_Cards":"5","Red_Cards":"0"},
{"Name":"Michail Antonio","Club":"West Ham United","Nationality":"ENG","Position":"FW","Age":"30","Matches":"26","Starts":"24","Mins":"1974","Goals":"10","Assists":"5","Passes_Attempted":"490","Perc_Passes_Completed":"66.5","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.52","xA":"0.11","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Craig Dawson","Club":"West Ham United","Nationality":"ENG","Position":"DF","Age":"30","Matches":"22","Starts":"22","Mins":"1925","Goals":"3","Assists":"0","Passes_Attempted":"718","Perc_Passes_Completed":"82.5","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.08","xA":"0.0","Yellow_Cards":"5","Red_Cards":"1"},
{"Name":"Jesse Lingard","Club":"West Ham United","Nationality":"ENG","Position":"MF,FW","Age":"27","Matches":"16","Starts":"16","Mins":"1421","Goals":"9","Assists":"4","Passes_Attempted":"669","Perc_Passes_Completed":"81.3","Penalty_Goals":"1","Penalty_Attempted":"2","xG":"0.32","xA":"0.09","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Issa Diop","Club":"West Ham United","Nationality":"FRA","Position":"DF","Age":"23","Matches":"18","Starts":"15","Mins":"1381","Goals":"2","Assists":"0","Passes_Attempted":"563","Perc_Passes_Completed":"84.4","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.02","xA":"0.0","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Saïd Benrahma","Club":"West Ham United","Nationality":"ALG","Position":"FW,MF","Age":"24","Matches":"30","Starts":"14","Mins":"1391","Goals":"1","Assists":"6","Passes_Attempted":"527","Perc_Passes_Completed":"78.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.15","xA":"0.28","Yellow_Cards":"0","Red_Cards":"0"}
,
{"Name":"Fabián Balbuena","Club":"West Ham United","Nationality":"PAR","Position":"DF","Age":"28","Matches":"14","Starts":"13","Mins":"1198","Goals":"1","Assists":"0","Passes_Attempted":"465","Perc_Passes_Completed":"76.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.05","xA":"0.0","Yellow_Cards":"1","Red_Cards":"1"}
,
{"Name":"Arthur Masuaku","Club":"West Ham United","Nationality":"COD","Position":"DF,FW","Age":"26","Matches":"12","Starts":"12","Mins":"1006","Goals":"0","Assists":"2","Passes_Attempted":"552","Perc_Passes_Completed":"80.1","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.03","xA":"0.17","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Sébastien Haller","Club":"West Ham United","Nationality":"CIV","Position":"FW","Age":"26","Matches":"16","Starts":"10","Mins":"937","Goals":"3","Assists":"0","Passes_Attempted":"252","Perc_Passes_Completed":"67.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.28","xA":"0.12","Yellow_Cards":"0","Red_Cards":"0"}
,
{"Name":"Mark Noble","Club":"West Ham United","Nationality":"ENG","Position":"MF","Age":"33","Matches":"21","Starts":"8","Mins":"712","Goals":"0","Assists":"0","Passes_Attempted":"429","Perc_Passes_Completed":"87.2","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.03","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Ryan Fredericks","Club":"West Ham United","Nationality":"ENG","Position":"DF,FW","Age":"27","Matches":"14","Starts":"6","Mins":"569","Goals":"1","Assists":"1","Passes_Attempted":"279","Perc_Passes_Completed":"72.8","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.05","xA":"0.19","Yellow_Cards":"2","Red_Cards":"0"},
{"Name":"Manuel Lanzini","Club":"West Ham United","Nationality":"ARG","Position":"MF,FW","Age":"27","Matches":"17","Starts":"5","Mins":"566","Goals":"1","Assists":"1","Passes_Attempted":"368","Perc_Passes_Completed":"88.9","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.18","xA":"0.14","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Ben Johnson","Club":"West Ham United","Nationality":"ENG","Position":"DF","Age":"20","Matches":"14","Starts":"5","Mins":"523","Goals":"1","Assists":"0","Passes_Attempted":"219","Perc_Passes_Completed":"70.3","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.06","xA":"0.04","Yellow_Cards":"1","Red_Cards":"0"},
{"Name":"Darren Randolph","Club":"West Ham United","Nationality":"IRL","Position":"GK","Age":"33","Matches":"3","Starts":"3","Mins":"270","Goals":"0","Assists":"0","Passes_Attempted":"66","Perc_Passes_Completed":"54.5","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Andriy Yarmolenko","Club":"West Ham United","Nationality":"UKR","Position":"FW,MF","Age":"30","Matches":"15","Starts":"1","Mins":"375","Goals":"0","Assists":"1","Passes_Attempted":"157","Perc_Passes_Completed":"79.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.1","xA":"0.23","Yellow_Cards":"3","Red_Cards":"0"},
{"Name":"Robert Snodgrass","Club":"West Ham United","Nationality":"SCO","Position":"FW,DF","Age":"32","Matches":"3","Starts":"0","Mins":"5","Goals":"0","Assists":"0","Passes_Attempted":"3","Perc_Passes_Completed":"100.0","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
{"Name":"Felipe Anderson","Club":"West Ham United","Nationality":"BRA","Position":"FW,MF","Age":"27","Matches":"2","Starts":"0","Mins":"3","Goals":"0","Assists":"0","Passes_Attempted":"6","Perc_Passes_Completed":"66.7","Penalty_Goals":"0","Penalty_Attempted":"0","xG":"0.0","xA":"0.0","Yellow_Cards":"0","Red_Cards":"0"},
];